version: '3.9'

services:

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

# Cadena de conexión a la base de datos PostgreSQL:
# postgresql://myuser:mypassword@localhost:5432/mydb
